---
settings:
  name: NetApp NFS Plug-in for VMware VAAI
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-tw,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn
sidebar:
  entries:
  - title: 適用於VMware VAAI文件的NetApp NFS外掛程式
    url: "/index.html"
  - title: 版本資訊
    url: "/releasenotes.html"
  - title: 安裝與設定
    entries:
    - title: 安裝適用於VMware VAAI的NetApp NFS外掛程式
      url: "/task-install-netapp-nfs-plugin-for-vmware-vaai.html"
    - title: 設定ONTAP 匯出原則以供支援透過NFS的VAAI
      url: "/task-configure-export-policies-for-clustered-data-ontap-to-allow-vaai-over-nfs.html"
  - title: 法律聲明
    url: "/reference-legal-notices.html"
